{application,ex_machina,
             [{registered,[]},
              {description,"A factory library by the creators of FactoryGirl"},
              {vsn,"1.0.2"},
              {modules,['Elixir.ExMachina','Elixir.ExMachina.Ecto',
                        'Elixir.ExMachina.EctoStrategy',
                        'Elixir.ExMachina.Sequence',
                        'Elixir.ExMachina.Strategy',
                        'Elixir.ExMachina.UndefinedFactoryError']},
              {applications,[kernel,stdlib,elixir,logger]},
              {mod,{'Elixir.ExMachina',[]}}]}.